vich_uploader:
    db_driver: orm

    mappings:
       logements_images:
           uri_prefix: /images/logements
           upload_destination: '%kernel.project_dir%/public/logements/images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
