controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

afficher_tranche_prix:
    path: /ajout_habitation
    controller: App\Controller\HabitationController::afficherTranchePrix
