controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

rechercher:
    path: /rechercher
    controller: App\Controller\rechercheController::resultatRecherche
